// Code generated by hertz generator.

package zgs_web_front

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
)

// HeartBeat .
// @router /status [GET]
func HeartBeat(ctx context.Context, c *app.RequestContext) {
	resp := "ok"
	c.JSON(200, resp)
}
