// Code generated by hertz generator.

package ZgsWebFront

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _heartbeatMw() []app.HandlerFunc {
	// your code...
	return nil
}
